version: '3.8'
services:
  ms-app:
    container_name: ms-notifications
    restart: always
    image: IMAGE_NAME
    ports:
      - "27192:9092"
    networks:
      - applications-network
    environment:
      - SPRING_PROFILES_ACTIVE=recette
      - providers.sendinblue.token=${{ secrets.SENDINBLUE_TOKEN }} 
      - providers.whatsapp.waba-id=${{ secrets.WHATSAPP_WABA_ID }} 
      - providers.whatsapp.phone=${{ secrets.WHATSAPP_PHONE }} 
      - providers.whatsapp.account-id=${{ secrets.WHATSAPP_ACCOUNT_ID }} 
      - providers.whatsapp.token=${{ secrets.WHATSAPP_TOKEN }} 
      - providers.twilio.account-id=${{ secrets.TWILIO_ACCOUNT_ID }} 
      - providers.twilio.account-secret=${{ secrets.TWILIO_ACCOUNT_SECRET }} 
      - providers.twilio.service-id=${{ secrets.TWILIO_SERVICE_ID }} 
      - providers.vonage.api_key=${{ secrets.VONAGE_API_KEY }} 
      - providers.vonage.api_secret=${{ secrets.VONAGE_API_SECRET }}

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-notifications.rule=Headers(`X-Host`, `api.notifications.chillo.fr`)"
      - "traefik.docker.network=applications-network"

networks:
  applications-network:
    external:
      name: applications-network

