spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
  mail:
    host: localhost #smtp-relay.brevo.com
    port: 25 #587
    username: accueil@chillo.tech
    password: pDXyM9QtTjYNJ8HV
  rabbitmq:
    host: 212.83.180.65
    port: 5672
    username: rbmq_admin
    password: administrator
    virtual-host: /
    template:
        default-receive-queue: "tech.notifications.queuelocal"

application:
  notifications:
    queue: "tech.messages.queuelocal"
  invitations:
    queue: "tech.invitations.queuelocal"
  messages:
    queue: "tech.messages.queuelocal"
  recipient:
   sms: "+33761705745"
   #email: simachille@gmail.com

providers:
  brevo:
    token: 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
  whatsapp:
    token: EAAIPrVhqxp0BO6p9qqt6by1lMrKjx9UB9tZAHdBgodTmKRKEzN7p4V6CdBeqcYQoif1MZAZA9TuryHdqDL6fQC2WMZBxZA6scicQziZAcRn4OG93gRNcbZAteuIDNd79svF6LddoM5ip9DUc9W1bNHjLlZBZCul5JWdGnX41zeaMoF9ZCSkxZCG0m2BbiXEJxePAciAfaS4y6LEHQnOW9vAYPO16FtZBYQqHxXOGDwZDZD
    account-id: 120793114319926
    waba-id: 120793114319926
    phone: 120089374390519
  twilio:
    account-id: ACc934f187de61e29cad93d56dad1f55a7
    account-secret: 94f692bd2c71718445591f7fa65b1025
    service-id: MG7d2363fb85d2c73240f82db2ac1a91f1
  vonage:
    api_key: 82dda85e
    api_secret: 4N7431cV36XN9TEO

feign:
  client:
    config:
      default:
        connectTimeout: 100000
        readTimeout: 100000
        loggerLevel: full
