spring:
  data:
    mongodb:
      host: db-zeeven
      authentication-database: admin

logging:
  level:
    org.springframework.security: ERROR
    tech.chillo.notifications: ERROR
org:
  springframework:
    web:
      filter:
        CommonsRequestLoggingFilter: ERROR
