
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin

  mail:
    host: localhost
    port: 25
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: false
          ssl:
            trust: "*"
          starttls:
            enable: true
    protocol: smtp
    test-connection: true
