application:
  messages:
    queue: "tech.messages.queue"
  notifications:
    queue: "tech.notifications.queue"

providers:
  sendinblue:
    host: https://api.sendinblue.com
    path: v3/smtp/email
    token: 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
  callback:
    host: https://api.notifications.chillo.fr/api/hooks
    path: ${providers.callback.host}/api/hooks
  whatsapp:
    token: EAAIPrVhqxp0BAGLS5au9e7DXTnOYcMgIZAg1mNQzWhvbXtD5NhzZCLSBn2fi6LA7mIksFc61PXQMq2MDWmdRPEZB16QyTjt5eZAlPb2P5bmvzhU9nYyPk3m4b4yZBCIspYKHToDUWZAlz3m1Jr2DaoZA0EnIrjQISk59E9KwtDMoiZCsjGC8cvhbJkx99Pbk05cRHjGMEaTVEgZDZD
    account-id: 120793114319926
    phone: 120089374390519
    host: https://graph.facebook.com/v16.0/${providers.whatsapp.phone}
    callback-path: ${providers.callback.path}/whatsapp
  twilio:
    host: https://api.twilio.com/2010-04-01/Accounts
    account-id: ACc934f187de61e29cad93d56dad1f55a7
    account-secret: bbebbea191b5ab4e0583dd06633d73da
    service-id: MG7d2363fb85d2c73240f82db2ac1a91f1
    callback-path: ${providers.callback.path}/twilio
  vonage:
    api_key: 82dda85e
    api_secret: 4N7431cV36XN9TEO
    callback-path: ${providers.callback.path}/vonage
  d7:
    CLIENT_ID: 8TTCIPUqAm4U99WVB7w59Q0BKnqKMQ32X1pHSWHA
    CLIENT_SECRET: KtnRDeF8cDEVOk9mD4EZYhftiZ7Ps8w6CiBZtfxZivPL0dbzbRl1E57b4bwhuyA7Bd0RVqs7k93g9YKqTbRyHxVOxZyhl5FvLChOBJ48T67lBUs8KeGwM9eOU6iaVt7i
    CLIENT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoLWJhY2tlbmQ6YXBwIiwic3ViIjoiNWY2NWY2YzctZDIzNC00MTIxLWE3NWItNzU1M2U0ZGE1YTMzIn0.FSEhMUPX65CKKQ7LOsAJw_kaa8DEGizb40mDp0oksqI
server:
  port : 9092
  servlet:
    context-path: /api
spring:
  application:
    name: ms-notifications
  rabbitmq:
    host: 212.83.180.65
    port: 5672
    username: rbmq_admin
    password: administrator
    virtual-host: prod-notifications
    connection-timeout: 10000
    template:
        default-receive-queue: "tech.notifications.queue"

  data:
    mongodb:
      host: localhost
      port: 27017
      database: ${spring.application.name}
  mail:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: false
          ssl:
            trust: "*"
          starttls:
            enable: true
    protocol: smtp
    test-connection: true

feign:
  client:
    config:
      default:
        connectTimeout: 100000
        readTimeout: 100000
        loggerLevel: full
