application:
  messages:
    queue: "tech.messages.queue"
  notifications:
    queue: "tech.notifications.queue"

providers:
  callback:
    host: https://api.notifications.chillo.fr/api/hooks
    path: ${providers.callback.host}/api/hooks
  sendinblue:
    host: https://api.brevo.com
    path: v3/smtp/email
  whatsapp:
    host: https://graph.facebook.com/v16.0/${providers.whatsapp.phone}
    template-host: https://graph.facebook.com/v16.0/${providers.whatsapp.waba-id}
    callback-path: ${providers.callback.path}/whatsapp
  twilio:
    host: https://api.twilio.com/2010-04-01/Accounts
    callback-path: ${providers.callback.path}/twilio
  vonage:
    callback-path: ${providers.callback.path}/vonage
server:
  port : 9092
  servlet:
    context-path: /api
spring:
  application:
    name: ms-notifications
  rabbitmq:
    virtual-host: prod-notifications
    connection-timeout: 10000
    template:
        default-receive-queue: "tech.notifications.queue"

  data:
    mongodb:
      host: localhost
      port: 27017
      database: ${spring.application.name}
  mail:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: false
          ssl:
            trust: "*"
          starttls:
            enable: true
    protocol: smtp
    test-connection: true

feign:
  client:
    config:
      default:
        connectTimeout: 100000
        readTimeout: 100000
        loggerLevel: full
logging:
  level:
    org.springframework.security: DEBUG
    tech.chillo.notifications: DEBUG
org:
  springframework:
    web:
      filter:
        CommonsRequestLoggingFilter: DEBUG
