application:
  messages:
    queue: "tech.messages.queue"
  notifications:
    queue: "tech.notifications.queue"

providers:
  whatsapp:
    token: EAAQB6FeiTJoBANewZAYjwrMiyjFonZC0JFBwZBfG6tlsT5KvNim5llZCs8EN26hD6fntKOM0YMXtzLwMnpUtrHSNrDM7hsZBAzlQdu1iBFFoZCGYVWL3DaKDXzMlnRDkWcKuY0Mdnlc0voyQOMDeZCxGuohUQiJX0K96c2TNjKAWfDmVGZAaU2wv61OtxRRPSzKZCOeHcDm7EYwZDZD
    account-id: 105401078979193
    phone: 102838372572347
    host: https://graph.facebook.com/v14.0/${providers.whatsapp.phone}
  twilio:
    host: https://api.twilio.com/2010-04-01/Accounts
    account-id: AC303b2ae3b08ffdadb7388fcb4417a34e
    account-secret: 8874919616ead2e8b86cbd9d5d4b0e0c
    service-id: MG73626e3bcb964eea28d61b9bb81cf3f4
  vonage:
    api_key: 82dda85e
    api_secret: 4N7431cV36XN9TEO
  d7:
    CLIENT_ID: 8TTCIPUqAm4U99WVB7w59Q0BKnqKMQ32X1pHSWHA
    CLIENT_SECRET: KtnRDeF8cDEVOk9mD4EZYhftiZ7Ps8w6CiBZtfxZivPL0dbzbRl1E57b4bwhuyA7Bd0RVqs7k93g9YKqTbRyHxVOxZyhl5FvLChOBJ48T67lBUs8KeGwM9eOU6iaVt7i
    CLIENT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoLWJhY2tlbmQ6YXBwIiwic3ViIjoiNWY2NWY2YzctZDIzNC00MTIxLWE3NWItNzU1M2U0ZGE1YTMzIn0.FSEhMUPX65CKKQ7LOsAJw_kaa8DEGizb40mDp0oksqI
server:
  port : 9092
  servlet:
    context-path: /api
spring:
  application:
    name: ms-notifications
  rabbitmq:
    host: 212.83.180.65
    port: 5672
    username: rbmq_admin
    password: administrator
    virtual-host: prod-notifications
    connection-timeout: 10000
    template:
        default-receive-queue: "tech.notifications.queue"

  data:
    mongodb:
      host: localhost
      port: 27017
      database: ${spring.application.name}
  mail:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: false
          ssl:
            trust: "*"
          starttls:
            enable: true
    protocol: smtp
    test-connection: true

feign:
  client:
    config:
      default:
        connectTimeout: 100000
        readTimeout: 100000
        loggerLevel: full
