server:
  port : 9092
  servlet:
    context-path: /api
spring:
  application:
    name: ms-notifications
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ${spring.application.name}
  mail:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: false
          ssl:
            trust: "*"
          starttls:
            enable: true
    protocol: smtp
    test-connection: true
